### ISSUE TITLE
Add an easy way to load extensions

### ISSUE THREAD

**Issue by IpProxyNeon** [HuyaneMatsu/hata#10]
I'd like to get an easy way to load extensions, since right now we have to do  `python
EXTENSION_LOADER = ExtensionLoader(client)

def add_extensions():
    async def entry(client, lib):
        commands=getattr(lib,'commands',None)
        if commands is not None:
            client.events.message_create.shortcut.extend(commands)
        
        entry=getattr(lib,'entry',None)
        if entry is not None:
            if is_coro(entry):
                await entry(client)
            else:
                entry(client)
            
        print(f'{lib.__name__} extension has been loaded!')
        
    async def exit(client, lib):
        commands=getattr(lib,'commands',None)
        if commands is not None:
            client.events.message_create.shortcut.unextend(commands)
        
        exit=getattr(lib,'exit',None)
        if exit is not None:
            if is_coro(exit):
                await exit(client)
            else:
                exit(client)

        print(f'{lib.__name__} extension has been unloaded!')

    for filename in os.listdir('./cogs/'):
        if filename.endswith('.py'):
            module_name='cogs.'+filename[:-3]   EXTENSION_LOADER.add(module_name, entry_point=entry, exit_point=exit)
add_extensions()
EXTENSION_LOADER.load_all().syncwrap().wait()` which is really annoying and is quite alot to try and remember, for discord.py all we have to do is `python
for file in os.listdir("./cogs/"):
    if file.endswith('.py'):
    client.load_extension(cogs.file.strip[:-3])` which is alot easier to remember, I'd think this would be a nice feature to implement since it'll simplify cog loading alot, for hata you could do `python
client.load_extension("path_of_cog", "the name of the eventlist to load")`

**Comment by IpProxyNeon** [comment]
I can't figure out syntax highlighting :/

**Comment by HuyaneMatsu** [comment]
~~The codeblock is broken.~~

Also these are not cogs, but I think I can do something about it.

**Comment by IpProxyNeon** [comment]
Oki, also, I don't really know what to call them
~I wanna call them `minihatas`~

**Comment by IpProxyNeon** [comment]
Do you think this is a good idea?

**Comment by HuyaneMatsu** [comment]
You do not really have to use that long code to load them, but I see the issue. I will add some auto naming and a method to instantly load the extensions as you add them.

**Comment by IpProxyNeon** [comment]
Oh Oki, thanks, how will the syntax be like?

**Comment by HuyaneMatsu** [comment]
```py
for file in os.listdir("./cogs/"):
    if file.endswith('.py'):
        client.load_extension(file.strip[:-3])
```

**Comment by IpProxyNeon** [comment]
Cool, it will be a really useful feature, but how about if you have multiple clients? Cuz I have Vega and Lily, so if I make an extension for Vega, how will I make Lily send a message?

**Comment by HuyaneMatsu** [comment]
Feels complete rewrite man.

**Comment by IpProxyNeon** [comment]
Wdym?
