### ISSUE TITLE
[Question] Add checks in decorator

### ISSUE THREAD

**Issue by IpProxyNeon** [HuyaneMatsu/hata#11]
Hello :P
I have an idea for a feature in Hata, I think it would be quite useful to be able to define a check in a decorator, e.g. `on_command(permissions=['permission 1', 'permission 2', 'etc'])`, and a way to access it via `client.events.commands["name"]["permissions"]` which would be quite nice, it would return a list, and if no permissions were passed, then it would return `[]`, this would be a nice feature to add, since it simplifies permission checks greatly, so what do you think?

**Comment by HuyaneMatsu** [comment]
Checks are already added and they can be accessed as `command.checks`. They can be run as well as `command.run_checks(client, message)`, which returns either True or False depening whether the checks passed.

Next version will bring category related checks as well. So be tuned!

**Comment by IpProxyNeon** [comment]
Oo, also, how do I use these checks? :sweat_smile: and does it return a list?

**Comment by HuyaneMatsu** [comment]
From Flandre, a command what uses checks.

```py
async def sync_avatar_description(client,message):
    prefix=client.events.message_create.prefix
    embed=Embed('sync_avatar',(
        'Hello there Esuto!\n'
        'This is a specific command for You, to sync the bot\'s avatar with '
        'the application\'s. I know, You might struggle with updating the '
        'bot\'s avatar the other way, so I made a command for it.\n'
        'Have a nice day!\n'
        f'Usage: `{prefix}sync_avatar`'
        ),color=FLAN_HELP_COLOR)
    await client.message_create(message.channel,embed=embed)

@commands(checks=[checks.owner_only()],description=sync_avatar_description)
async def sync_avatar(client,message):
    avatar_url=client.application.icon_url_as(ext='png',size=4096)
    if avatar_url is None:
        await client.message_create(message.channel,'The application has no avatar set.')
        return True
    
    avatar = await client.download_url(avatar_url)
    await client.client_edit(avatar=avatar)
    
    await client.message_create(message.channel,'Avatar synced.')
    return False
```

Accessing it returns a list now, but after the next commit it ll return None if empty.

**Comment by IpProxyNeon** [comment]
Oh ok, how about if I want to compare it to, let's say, perms for managing a channel?

**Comment by HuyaneMatsu** [comment]
```py
checks.has_permissions(Permission().update_by_keys(manage_channel=True))
```
or
```py
checks.has_guild_permissions(Permission().update_by_keys(manage_channel=True))
```

**Comment by IpProxyNeon** [comment]
Is `has_permissions` for a channel only?

**Comment by HuyaneMatsu** [comment]
Yuss.

**Comment by IpProxyNeon** [comment]
Thanks!
