### ISSUE TITLE
[SUGGESTION] Add a default help command

### ISSUE THREAD

**Issue by Technisha** [HuyaneMatsu/hata#14]
I think a default help command (similar to Discord.py's help command) would be a good idea. Maybe just to show users how their help command should be structured? The structure would probably be like
```yaml
CATEGORY:
  - Command1 <args> - <description>
  - Command2 <args> - <description>
```

**Comment by HuyaneMatsu** [comment]
I have no clue what Discord.py default help command does, hope you can give clear configuration settings and visual examples.

**Comment by Technisha** [comment]
Well, for configuration settings i don't have any ideas for, but for the visual examples i can provide them once i implement them in my bot

**Comment by HuyaneMatsu** [comment]
With help of Est we desided how the command should work, so this issue will be closed soon. :ok_hand:
