### ISSUE TITLE
Custom endpoint base URL

### ISSUE THREAD

**Issue by Technisha** [HuyaneMatsu/hata#16]
I think a way to change the base URL for endpoints would be a good idea. Because there's things like https://gitlab.com/litecord/litecord which allow people to test their bots out on private discord instances. I think it'd be a neat feature. It'd probably be changed like
`Client(base_url="https://discord.com/api")`
Obviously, `base_url` would be changeable to anything you want. Like a private instance of https://gitlab.com/litecord/litecord

**Comment by codic12** [comment]
You'd also want to check if an endpoint was actually implemented, eg if some thing didn't implement roles (which is `/guilds/{guild.id}/members/{user.id}/roles/{role.id}`, if i recall correctly), a 404 would be thrown, but you should throw a proper error instead (eg ApiUnimplementedError or something).

Also, if you have this, you also need a way to change the gateway uri (default is wss://discord.gg)

**Comment by Technisha** [comment]
Oh yeah-

**Comment by HuyaneMatsu** [comment]
Will env variables be good for you?

**Comment by Technisha** [comment]
Not for my use case specifically, because i need to be able to have one discord client, and one litecord client in the same app

**Comment by HuyaneMatsu** [comment]
Hata relies on shared ratelimit informations, so more runtime endpoints would invalidate eachother. With this in mind, I do not think I will add a feature like this.

**Comment by codic12** [comment]
No, but you would only be connecting to one endpoint at a given time.

**Comment by HuyaneMatsu** [comment]
Connecting to one is OK. I could add that if still interested.

**Comment by Technisha** [comment]
Okay. How would that work?

**Comment by HuyaneMatsu** [comment]
Env variables? Or any better idea?

**Comment by codic12** [comment]
Maybe a variable in the function that sends the identify payload would work

**Comment by Technisha** [comment]
Couldn't you make the url changeable in the `Client` class?

**Comment by HuyaneMatsu** [comment]
> Couldn't you make the url changeable in the `Client` class?

Hata uses real global cache, what means entities are not bound to any client, like in most of the other wrappers, which use connection based cache :cough: .

So basically to overwrite every url correctly it would be needed to modify them before `hata.discord.http.URLS` module is initialized, so when loading the library.

> Maybe an argument in the function that sends the identify payload would work

Identify has nothing to do with urls.

**Comment by codic12** [comment]
Identify payload is used for the gateway websocket uri, and I assume the func that runs the bot sends an identify. 
Ah, it uses a global cache? Then you would only be able to change it once an instance, yeah; I typically use a connection based cache

**Comment by HuyaneMatsu** [comment]
> Identify payload is used for the gateway websocket uri, and I assume the func that runs the bot sends an identify.

Identify is a websocket payload towards Discord, but I get what you mean. I will link the gateway urls to `hata.discord.http.URLS`  (should have done it before already).

> Ah, it uses a global cache? Then you would only be able to change it once an instance, yeah; I typically use a connection based cache

At the case of more clients, the saved ram by global cache can be astronomical compared to connection based ones. This is one of the selling features of the wrapper. Tho ram usage will be further decreased soon :3
