### ISSUE TITLE
[FEATURE] Custom Stdout/err/in

### ISSUE THREAD

**Issue by Technisha** [HuyaneMatsu/hata#32]
Something that'd be pretty nifty would be wrappers around a channel that could be used is `stdout`/`stderr`/`stdin` in Hata. An example would be
```python
hstdout, hstderr, hstdin = get_channel_std(Client, Channel)
```
That could be used exactly like `stdout`/`stderr`/`stdin` as drop in alternatives for anything else that need std, so redirecting logging to a channel, or a shell like `bash`

**Comment by ToxicKidz** [comment]
Implemented in https://github.com/HuyaneMatsu/hata/commit/b494cebe934eeda926867b63530251461ae99186.

**Comment by HuyaneMatsu** [comment]
Will close of the implementation matches the expectation.

**Comment by Technisha** [comment]
I'll test it out later! :D
