### ISSUE TITLE
[LONG-TERM] [SUGGESTION] Split up Hata into different repos

### ISSUE THREAD

**Issue by Technisha** [HuyaneMatsu/hata#34]
Hata currently is amazing, but it's _all_ in one single repo. I think splitting it up into `async`, `websockets`, `html server` would be a LOT better, because that way people can use your async without downloading everything else, or the same with `websockets`. Having multiple projects also makes it easier to update code independent from eachother, so you don't have to change a while file to make one thing work, for example.

**Comment by HuyaneMatsu** [comment]
Archiving issue.

**Comment by HuyaneMatsu** [comment]
The whole async part of hata will be cut out into it's own package, resolving this issue partially.

**Comment by Mythical-Forest-Collective** [comment]
Cool! (This is my new GitHub account btw)
Will everything be split up eventually? So websocket client/server (they can be bundled together), http requests, etc?

**Comment by HuyaneMatsu** [comment]
Cannot guarantee.

**Comment by Mythical-Forest-Collective** [comment]
That's fair enough

**Comment by HuyaneMatsu** [comment]
Opened a new [repo](https://github.com/HuyaneMatsu/scarletio) for hata's async. Help is welcome to make it a better stand-alone library.
