### ISSUE TITLE
[LONG-TERM] [SUGGESTION] Add AnyIO support to Hata

### ISSUE THREAD

**Issue by Technisha** [HuyaneMatsu/hata#35]
This is a long term suggestion, but adding AnyIO support to Hata might be a good idea, since then libaries that use a specific library or use AnyIO would also work in Hata. And while Hata async is faster then everything else, this also proves to others how much better it is (also gives you the option to use AnyIO in other projects and use Hata's async)

**Comment by HuyaneMatsu** [comment]
Pushed, will be resolved next deploy.
