### ISSUE TITLE
ClientWrapper stuff

### ISSUE THREAD

**Issue by WeMayNeverKnow** [HuyaneMatsu/hata#36]
How about add normal functionalities of a client to the client wrapper and if we defined a client's own we could overwrite stuff.

For example I want all my bots to have the same help cmd without defining in every single one.

Same for slash cmds

**Comment by HuyaneMatsu** [comment]
> How about add normal functionalities of a client to the client wrapper and if we defined a client's own we could overwrite stuff.

https://github.com/HuyaneMatsu/hata/projects/2#card-49630743

> For example I want all my bots to have the same help cmd without defining in every single one.

Adding commands to each is possible.

> Same for slash cmds

Same for slash commands.
