### ISSUE TITLE
Docs search stuff

### ISSUE THREAD

**Issue by WeMayNeverKnow** [HuyaneMatsu/hata#37]
I have been using docs for a long time now and I have ideas on how can we improve on it.

On the docs search engine when I searched:
- the engine sometimes doesn't search for lower case if I have an upper case in the keywords
- sometimes it's hard to differentiate which one is in methods and which is in property it's kinda hard to know since they look the same

It might be a good idea to search the docstrings to rather than just the topic/method/class name etc.

**Comment by HuyaneMatsu** [comment]
Do you wish to create OR to fix it?

**Comment by WeMayNeverKnow** [comment]
Ofcourse!!!

**Comment by WeMayNeverKnow** [comment]
Not
