### ISSUE TITLE
Embed Gayness

### ISSUE THREAD

**Issue by WeMayNeverKnow** [HuyaneMatsu/hata#39]
Why are there two different methods which probably does the same thing for embeds?

https://huyanematsu.pythonanywhere.com/docs/hata/discord/embed/Embed

Ex.
Embed.add_footer
Embed.set_footer
There are lots more OwO

**Comment by HuyaneMatsu** [comment]
By using `.add_footer` and not `.set_footer` you declare you are a real chad. Should I remove non chad methods?

**Comment by WeMayNeverKnow** [comment]
Yeh that would be nice. Just make sure no bot will die afterwards

**Comment by HuyaneMatsu** [comment]
Resolved.
