### ISSUE TITLE
[Bug] Row.copy_with raises NameError

### ISSUE THREAD

**Issue by catzoo** [HuyaneMatsu/hata#48]
### Description

With my code, I decided to try to copy Row only with different components. When I ran `copy_with`, it came back with an error. I thought at first this was my code since it was a bit messy at the time. So, I tested it in a different file without running the bot, the same error came back.

The reproduction code below is what the test file included. It would be easier to create a new Row object rather than copying it, but I was mainly messing around with components and seeing what I can do.

### Reproduction Code

```python
from hata import BUILTIN_EMOJIS
from hata.ext.slash import Button, Row

# Paginator buttons
PAGE_FIRST = Button(emoji=BUILTIN_EMOJIS["track_previous"])
PAGE_LAST = Button(emoji=BUILTIN_EMOJIS["track_next"])
PAGE_NEXT = Button(emoji=BUILTIN_EMOJIS["arrow_right"])
PAGE_PREVIOUS = Button(emoji=BUILTIN_EMOJIS["arrow_left"])

PAGE_BUTTONS = Row(PAGE_FIRST, PAGE_PREVIOUS, PAGE_NEXT, PAGE_LAST)

TEST = PAGE_BUTTONS.copy_with(components=[PAGE_FIRST])
```

### Expected behaviour

`copy_with` return the new object with different components.

### Actual behaviour

This error came up:
```py
Traceback (most recent call last):
  File "C:\Users\Catzoo Bob\Desktop\Github\discord-channel-bot\bot\test.py", line 12, in <module>
    TEST = PAGE_BUTTONS.copy_with(components=[PAGE_FIRST])
  File "C:\Users\Catzoo Bob\Desktop\Github\discord-channel-bot\bot\bot-env\lib\site-packages\hata\discord\interaction\components.py", line 658, in copy_with
    self = object.__new__(cls)
NameError: name 'cls' is not defined
```

### System information

```
Hata version: 1.1.101
Platform: Windows-10-10.0.19042-SP0
Python implementation: cpython
Python version: 3.9 final
```

**Comment by HuyaneMatsu** [comment]
I am sorry because of the bug. The new version on pypi has it already fixed. 👍🏻 

If you are trying to do paginations, the slash extension has premade one, tho it is not yet documented.

**Comment by catzoo** [comment]
oh no worries. When I first found the bug, I figured out a better / easier way of what I was attempting to do.

Didn't know about slash pagination, i'll check it out. Thanks
