### ISSUE TITLE
[Feature Request] Object binding

### ISSUE THREAD

**Issue by Mythical-Forest-Collective** [HuyaneMatsu/hata#62]
### Summary

A cool hata feature would be the ability to bind objects to an existing object, and depending on what that is, have it be initialised and share the data of the class that an object has been bound to. This would also need a way to detect if the object that is meant to be bound to an object is a class and needs to be initialised, including if it is asynchronous or not.

### Ideal Solution

A bind function could loosely be implemented with a method that accepts 3 parameters. The first being the object being bound to, the second being the target object to bind, and the third being the initialised name of the object.

### Use case code

```python
from hata import User, bind

class Inventory(object):
    def __init__(self, parent_self):
        self.user = parent_self
        self.inv = []

    def add_item(self, name):
        self.inv.append(name)

    def give_user(self, item, recipient):
        del self.inv[self.inv.index(item)]
        recipient.inventory.add_item(item)


bind(User, Inventory, 'inventory')  # Parent object, new class, initialised object name

# Note this is a very bad example. This should also be doable with functions and variables, simply just adding them to the parent object.
```

### Alternative solutions

While i could simply just keep them separate, it would be more convenient and beneficial to be able to bind related objects together, as they will never be used without eachother.

**Comment by HuyaneMatsu** [comment]
Coming soon TM

**Comment by WizzyGeek** [comment]
+1 on this, would make user data handling very elegant

**Comment by HuyaneMatsu** [comment]
The feature has been added.
