### ISSUE TITLE
Documentation Improvement

### ISSUE THREAD

**Issue by m0nk3ybraindead** [HuyaneMatsu/hata#65]
### Summary

1. It's hard to navigate around the docs

2. The search engine of the docs website is kinda strict
(It makes it hard to find certain things)

3. The other things aren't in the docs website (most people rely on the docs website rather than the github one)

### Ideal Solution

1. Add a sidebar like where we can see and/or fold other topics.
 
2. Don't make it that much strict.

3. Add the tutorials. Maybe add examples on how to use other useful things. **Put everything in one place.**

### Alternative solutions

Recreate the whole website maybe on github docs

### Additional Context

This issue is the input I took from other people who don't know what exactly hata is yet and my own feedback.

**Comment by m0nk3ybraindead** [comment]
Would you mind making a repository for a new website or just linking the old one. Thanks!

**Comment by HuyaneMatsu** [comment]
I would like you to create a new one. I already started rewriting the current docs site a few days ago.

**Comment by m0nk3ybraindead** [comment]
Please link the old code of the website so I can have references thanks!

**Comment by HuyaneMatsu** [comment]
The documentation parser can be found [here](https://github.com/HuyaneMatsu/hata/tree/master/hata/ext/patchouli) and the site [here](https://github.com/HuyaneMatsu/Koishi/tree/master/web/modules/hata_docs).

**Comment by m0nk3ybraindead** [comment]
The new docs it better.
