### ISSUE TITLE
[Bug] Can't use load_opus

### ISSUE THREAD

**Issue by FoxeiZ** [HuyaneMatsu/hata#67]
### Description

hata try to load opus lib at `.venv\\lib\\site-packages\\hata\\discord\\voice\\bin\\libopus-0.x64.dll` instead of `.venv\\lib\\site-packages\\hata\\discord\\bin\\libopus-0.x64.dll`

### Reproduction Code

```python
from hata.discord.voice.opus import load_opus

load_opus()
```

### Expected behaviour

the opus lib load correctly

### Actual behaviour

```py
FileNotFoundError("Could not find module '.venv\\lib\\site-packages\\hata\\discord\\voice\\bin\\libopus-0.x64.dll' (or one of its dependencies). Try using the full path with constructor syntax.")
```

### System information

Hata version: 1.1.132
Platform: Windows-7-6.1.7601-SP1
Python implementation: cpython
Python version: 3.8 final

**Comment by HuyaneMatsu** [comment]
Thanks for reporting this issue.

**Comment by HuyaneMatsu** [comment]
Should be fixed.
