### ISSUE TITLE
[Feature request] Client creating from class

### ISSUE THREAD

**Issue by m0nk3ybraindead** [HuyaneMatsu/hata#69]
### Summary

I am trying to use a factory pattern and trying to make a create_app function. But I realized that I have to make so many parameters.

### Ideal Solution

We could just make a config class that has the parametert

### Use case code

```python
from hata import Client
import os

class NueConfig:
  token = os.getenv('token')
  ...

Nue = Client.from_class(NueConfig)

# in my use case

def create_app(config, setup_slash=True, setup_commands=True, ...):
    client = Client.from_class(config)
    if setup_slash:
        setup_ext_slash(client)
    if setup_commmands:
        ....
    return client
```

### Alternative solutions

we could also have Client.from_dict()

### Additional Context

Factory pattern

**Comment by HuyaneMatsu** [comment]
The client constructor already accepts plugged in parameters. Even if you pass extra parameter no error will be dropped, only a warnings about the unused parameters.

If you have a config dict, doing this is completely fine:

```py
Nue = Client(**config)
```

Here is a full list of expected parameters (by default):

- token
- secret
- client_id
- application_id
- activity
- status
- is_bot
- shard_count
- intents
- additional_owners
- extensions
- http_debug_options
- name
- discriminator
- avatar / avatar_hash & avatar_type
- banner / banner_hash & banner_type
- banner_color
- flags

----

The `extensions` parameter defines which extensions are added to the client. These extensions are looked up from `hata.ext` folder. The extensions are imported and it expects them to call `register_setup_function` with their setup function, required and optional parameters.

If all extension is found and all required parameter is satisfied (from the extra parameters), the client's constructor runs, then the extension setuppers are called.

If you wonder what extensions are shipped & setuppable with the base library:

| name | Required parameters | Optional parameters |
|--|--|--|
| commands (deprecated) | - | prefix, lite, ignorecase, mention_prefix, default_category_name, category_name_rule, command_name_rule, precheck |
| command_utils | - | - |
| commands_v2 | prefix | precheck, mention_prefix_enabled, category_name_rule, command_name_rule, default_category_name, prefix_ignore_case |
| slash | - | delete_commands_on_unload, use_default_exception_handler, random_error_message_getter |
| top.gg | top_gg_token | auto_post_bot_stats, raise_on_top_gg_global_rate_limit |

----

### Conclusion

![client-constructor-meme](https://user-images.githubusercontent.com/37266847/154795649-fc9f7ff0-76ac-41b4-9029-690cbf1a8bda.jpeg)

**Comment by m0nk3ybraindead** [comment]
Aight thanks I guess
