### ISSUE TITLE
[Bug] Custom ActivityRich causes TypeError

### ISSUE THREAD

**Issue by Coryf88** [HuyaneMatsu/hata#76]
### Description

Creating an ActivityRich, with a custom type_, causes a TypeError.

### Reproduction Steps

1. Execute reproduction code.

### Reproduction Code

```python
import hata
hata.ActivityRich('', type_=hata.ACTIVITY_TYPES.custom)
```

### Expected behaviour

``ValueError: `type_` can be any of: 0, 1, 2, 3, 5, got 4.``

### Actual behaviour

`TypeError: sequence item 0: expected str instance, int found`

### System information

Hata version: 1.2.14
Scarletio version: 1.0.27
Platform: Windows-10-10.0.19041-SP0
Python implementation: cpython
Python version: 3.9 final

**Comment by HuyaneMatsu** [comment]
Fixed, thanks for reporting 👍🏻
