### ISSUE TITLE
Make a way to get any type class Json serializable

### ISSUE THREAD

**Issue by Jekabs123** [HuyaneMatsu/hata#8]
Make something like `Object.toJson()` return a JSON of all the data.

Or a way to get raw data that was received from the discord's api.

**Comment by IpProxyNeon** [comment]
There's probably a way to do this already, but idk, maybe it's not, but probably is

**Comment by gsbhasin123** [comment]
@Jekabs123 Ruby uses Object, Python uses object :P

**Comment by HuyaneMatsu** [comment]
> Make something like Object.toJson() return a JSON of all the data.

[Above comment](https://github.com/HuyaneMatsu/hata/issues/8#issuecomment-579010425) + `.toJson` looks like a nice java method name. :P

Python uses `JSONEncoder` subclasses to implement this behaviour. It is doable, but a lot of effort.

Still a question, if it should return:
- Data to be saved.
- Data as Discord would send it.

> Or a way to get raw data that was received from the discord's api.

Low level hook, like this wont be provided. If you have any issue about datamissprocessing or if unreasoned data is sent to an event, you can open an issue about it.

If you still want to catch the received data, it is 1st processed at [gateway.py](https://github.com/HuyaneMatsu/hata/blob/master/hata/gateway.py). The methods are documented at reference docs too, so finding the correct method to replace should be easy.

**Comment by IpProxyNeon** [comment]
Honestly @Jekabs123 if your only looking to get a JSON format of all the data, it's better to make a crappy system to get messages from Discord's API directly

**Comment by gsbhasin123** [comment]
`.toJson` is using 'camel case'. It's used by a lot of programmers XD

**Comment by gsbhasin123** [comment]
@IpProxyNeon Honestly
- you're, not your
- nah, it'd be better to extend Hata yourself or do what @HuyaneMatsu said

**Comment by IpProxyNeon** [comment]
Stop correcting my grammar!

**Comment by gsbhasin123** [comment]
Grammer, or grammar?
jkjk

**Comment by HuyaneMatsu** [comment]
Please stop bullying eachother on grammar. I have dad jokes to scare you from it:

> .toJson is using 'camel case'. It's used by a lot of programmers XD

Son : *Daddy, can we have `camelCase` at home?*

Camel case at home: `CamelCase`

**Comment by gsbhasin123** [comment]
????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????/
it is not bullying

**Comment by IpProxyNeon** [comment]
Yeah, don't bully me @gsbhasin123

**Comment by gsbhasin123** [comment]
I WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOUI WILL BULLY YOU

**Comment by gsbhasin123** [comment]
Courtesy of ruby :P

**Comment by IpProxyNeon** [comment]
@HuyaneMatsu he is bullying me TwY

**Comment by gsbhasin123** [comment]
deleted the message TwT

**Comment by IpProxyNeon** [comment]
HuyaneMatsu can still see it :/

**Comment by gsbhasin123** [comment]
@Proxy @IpProxyNeon How though

**Comment by IpProxyNeon** [comment]
https://discordapp.com/channels/388267636661682178/555476090382974999/671523795508527166

**Comment by gsbhasin123** [comment]
Eh
Who cares
:}

**Comment by IpProxyNeon** [comment]
Can we close this issue now? :P

**Comment by gsbhasin123** [comment]
ask auser0 @IpProxyNeon

**Comment by gsbhasin123** [comment]
All deleted :(

**Comment by HuyaneMatsu** [comment]
@Jekabs123 If you are not interested in the topic anymore, or you wont answer on detailed questions, I ll close this issue.

Open issues hurt my eyes.

**Comment by Jekabs123** [comment]
Oh, I will close this because I no longer need it.
