### ISSUE TITLE
[FEATURE REQUEST] a description/text field on the command decorator

### ISSUE THREAD

**Issue by IpProxyNeon** [HuyaneMatsu/hata#9]
I need a way to store text in the command decorator and need it so I can get it from the case of the command, maybe it could be an extra field in `client.events.message_create.commands`? It would be very useful to be able to store text or even a dict about commands, if it can store any data type, that would be preferable since I can easily adapt this to my commands

**Comment by IpProxyNeon** [comment]
Is this too long?

**Comment by HuyaneMatsu** [comment]
Would that be good if `client.events.message_create.commands` would store `Command` objects (instead of tuple, like now), which would have 3 attributes : `needs_content`, `command` and `desc` (or `description` if that is preferred).

The `desc` attribute could be added like:

1.: docstring
```py
@on_command
async def nice_command(client, message):
    """Cakes are great, change my mind."""
    pass
```

> Ofc docstring would be normalized to the correct indent level.

2.: Like `case`
```py
@on_command(desc='Cakes are great, change my mind.')
async def nice_command(client, message):
    pass
```

If no `desc` is passed, the default value would be `None`.

**Comment by IpProxyNeon** [comment]
Let's say we are using example number 2, would you be able to pass a dict to it? That would be the easiest method for me, if not, then example 1 would be the ideal way, tho passing a dict would be the ideal implementation

**Comment by HuyaneMatsu** [comment]
Both would be implemented and without typechecks ofc.

**Comment by IpProxyNeon** [comment]
Oh ok, that would be cool, so how would I access the description? `client.events.message_create.commands['the command of choice'].desc`?

**Comment by HuyaneMatsu** [comment]
Like that :ok_hand:

**Comment by IpProxyNeon** [comment]
Coolio, this seems like a perfect solution to me, thanks!

**Comment by HuyaneMatsu** [comment]
Implemented as `description` instead of `desc` for making it cleaner. :ok_hand:

**Comment by IpProxyNeon** [comment]
Thank you!
